export const SLOT_INSERT_DURATION = 150;
export const SLOT_INSERT_DURATION_ALT = 200;
export const SLOT_TO_SPACE_DURATION = 700;
export const WELL_RETURN_DURATION = 300;
export const BOARD_COLOR_CHANGE_DURATION = SLOT_TO_SPACE_DURATION + 100;

export const WINNER_V1_DELAY = 1000;
export const WINNER_V1 = 700;
export const WINNER_V0_DELAY = 100;
export const WINNER_V0 = 700;

export const WAIT_FOR_WINNER_CHECK = WINNER_V1_DELAY + WINNER_V0_DELAY;

export const WINNER_BASE_DELAY = 150;
