export const SLOT_INSERT_DURATION = 150;
export const SLOT_INSERT_DURATION_ALT = 200;
export const SLOT_TO_SPACE_DURATION = 700;
export const WELL_RETURN_DURATION = 300;
export const BOARD_COLOR_CHANGE_DURATION = SLOT_TO_SPACE_DURATION + 100;
