/**
 * Builds the initial mapping of well cell IDs to piece IDs.
 * Team One: wells at rows 9-16, cols 9-11 → pieces 0-23
 * Team Two: wells at rows 17-24, cols 12-14 → pieces 24-47
 *
 * These IDs must match the IDs generated by TeamWellGrid.
 */
export function buildInitialWellPieceLocations(): Record<string, string> {
  const map: Record<string, string> = {};
  let pieceNum = 0;
  for (let c = 9; c <= 11; c++) {
    for (let r = 9; r <= 16; r++) {
      map[`${r}-${c}`] = String(pieceNum++);
    }
  }
  for (let c = 12; c <= 14; c++) {
    for (let r = 17; r <= 24; r++) {
      map[`${r}-${c}`] = String(pieceNum++);
    }
  }
  return map;
}
