import { ColorThemeType } from "@/types/themes/colorTheme";

export const CLASSIC_COLOR: ColorThemeType = {
  TEAM_ONE_COLOR: "#ffffff",
  TEAM_TWO_COLOR: "#000000",
  TEAM_ONE_WINNER_COLOR: "#fdffd0ff",
  TEAM_TWO_WINNER_COLOR: "#967d00ff",
  CORNER_COLOR_ONE: "#ffffff",
  CORNER_COLOR_TWO: "#000000",
  WELL_GRID_BG_COLOR_ONE: "#6E2C00",
  WELL_GRID_BG_COLOR_TWO: "#6E2C00",
  WELL_BG_COLOR_ONE: "#377a67ff",
  WELL_BG_COLOR_TWO: "#377a67ff",
  SLOT_BORDER_COLOR: "#C0C0C0",
  SLOT_FOREGROUND_COLOR: "#6E2C00",
  PIECE_TO_SLOT_COLOR: "#C0C0C0",
  ODD_SPACE_COLOR: "#ffffff",
  EVEN_SPACE_COLOR: "#d1fae5",
  FELT_TOP: "#065f46",
};
